# Generated by Django 5.1.4 on 2026-09-01 00:00

import django.core.files.storage
import django.db.models.deletion
import invitation.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ism')),
                ('honorific', models.CharField(blank=True, help_text='aka, opa, xola, oila', max_length=40, verbose_name='Murojaat')),
                ('code', models.CharField(blank=True, max_length=24, unique=True, verbose_name='Kod')),
                ('seats', models.PositiveSmallIntegerField(default=2, verbose_name='Necha kishiga')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Ichki izoh')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Birinchi ochilgan')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name='Necha marta ochilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mehmon',
                'verbose_name_plural': 'Mehmonlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('mode', models.CharField(choices=[('invitation', "Taklifnoma (to'ygacha)"), ('thanks', "Rahmat sahifasi (to'ydan keyin)")], default='invitation', max_length=20, verbose_name='Sahifa rejimi')),
                ('groom_name', models.CharField(max_length=80, verbose_name='Kuyov ismi')),
                ('bride_name', models.CharField(max_length=80, verbose_name='Kelin ismi')),
                ('event_at', models.DateTimeField(verbose_name="To'y sanasi va soati")),
                ('welcome_time', models.CharField(blank=True, help_text='Masalan: 18:00', max_length=40, verbose_name='Kutib olish')),
                ('venue_name', models.CharField(max_length=160, verbose_name="To'yxona nomi")),
                ('venue_address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('map_url', models.URLField(blank=True, help_text='Yandex yoki Google Maps', verbose_name='Xarita havolasi')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('invite_text', models.TextField(blank=True, verbose_name='Taklif matni')),
                ('dress_code', models.CharField(blank=True, max_length=160, verbose_name='Dress code')),
                ('contact_one_name', models.CharField(blank=True, max_length=80, verbose_name='1-aloqa: ism')),
                ('contact_one_phone', models.CharField(blank=True, max_length=40, verbose_name='1-aloqa: telefon')),
                ('contact_two_name', models.CharField(blank=True, max_length=80, verbose_name='2-aloqa: ism')),
                ('contact_two_phone', models.CharField(blank=True, max_length=40, verbose_name='2-aloqa: telefon')),
                ('hero_image', models.ImageField(blank=True, upload_to=invitation.models.hero_path, verbose_name='Bosh rasm')),
                ('music', models.FileField(blank=True, upload_to=invitation.models.music_path, verbose_name='Fon musiqasi')),
                ('rsvp_open', models.BooleanField(default=True, verbose_name='Javob berish ochiq')),
                ('uploads_open', models.BooleanField(default=False, verbose_name='Rasm yuklash ochiq')),
                ('thanks_title', models.CharField(blank=True, max_length=160, verbose_name='Rahmat sarlavhasi')),
                ('thanks_text', models.TextField(blank=True, verbose_name='Rahmat matni')),
                ('upload_hint', models.TextField(blank=True, verbose_name="Yuklash bo'limi izohi")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "To'y",
                'verbose_name_plural': "To'y sozlamalari",
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Sarlavha')),
                ('date_label', models.CharField(blank=True, max_length=60, verbose_name='Sana matni')),
                ('text', models.TextField(blank=True, verbose_name='Matn')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='invitation.wedding')),
            ],
            options={
                'verbose_name': 'Voqea',
                'verbose_name_plural': 'Sevgi tarixi',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ism')),
                ('attending', models.BooleanField(default=True, verbose_name='Keladi')),
                ('seats', models.PositiveSmallIntegerField(default=1, verbose_name='Necha kishi')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('message', models.TextField(blank=True, verbose_name='Tilak')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsvps', to='invitation.guest')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='invitation.wedding')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Mehmon javoblari (RSVP)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='guest',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='invitation.wedding'),
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=invitation.models.gallery_path, verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='Izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='invitation.wedding')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuestUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_name', models.CharField(max_length=120, verbose_name='Yuklovchi')),
                ('folder_name', models.CharField(blank=True, max_length=140, verbose_name='Papka')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('.')), upload_to=invitation.models.guest_upload_path, verbose_name='Fayl')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Asl nomi')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Turi')),
                ('size', models.BigIntegerField(default=0, verbose_name='Hajmi (bayt)')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('is_video', models.BooleanField(default=False, verbose_name='Video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='invitation.guest')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='invitation.wedding')),
            ],
            options={
                'verbose_name': 'Yuklangan fayl',
                'verbose_name_plural': 'Mehmonlar yuklagan fayllar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['folder_name'], name='invitation__folder__948617_idx')],
            },
        ),
    ]
