# Generated by Django 5.1.4 on 2026-09-01 20:21

import django.core.files.storage
import django.db.models.deletion
import invitation.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestupload',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/xalil/Desktop/jalolliddin/backend/private_media')), upload_to=invitation.models.guest_upload_path, verbose_name='Fayl'),
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ism')),
                ('text', models.TextField(verbose_name='Tilak')),
                ('is_visible', models.BooleanField(default=True, help_text="Belgini olsangiz sahifadan yo'qoladi.", verbose_name="Ko'rinadi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishes', to='invitation.guest')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='invitation.wedding')),
            ],
            options={
                'verbose_name': 'Tilak',
                'verbose_name_plural': 'Tilaklar',
                'ordering': ['-created_at'],
            },
        ),
    ]
