# Generated by Django 5.1.4 on 2026-09-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_alter_guestupload_file_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='date_label_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='Sana matni (EN)'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='Matn (EN)'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='title_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Sarlavha (EN)'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='bride_name_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='Kelin ismi (EN)'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='dress_code_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Dress code (EN)'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='groom_name_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='Kuyov ismi (EN)'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='invite_text_en',
            field=models.TextField(blank=True, verbose_name='Taklif matni (EN)'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='show_english',
            field=models.BooleanField(default=True, help_text="Belgini olsangiz sahifada til almashtirish tugmasi ko'rinmaydi.", verbose_name='Ingliz tili tugmasi'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='thanks_text_en',
            field=models.TextField(blank=True, verbose_name='Rahmat matni (EN)'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='thanks_title_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Rahmat sarlavhasi (EN)'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='upload_hint_en',
            field=models.TextField(blank=True, verbose_name="Yuklash bo'limi izohi (EN)"),
        ),
        migrations.AddField(
            model_name='wedding',
            name='venue_address_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Manzil (EN)'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='venue_name_en',
            field=models.CharField(blank=True, max_length=160, verbose_name="To'yxona nomi (EN)"),
        ),
    ]
