# Generated by Django 5.1.4 on 2026-09-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_timelineevent_date_label_en_timelineevent_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Sarlavha')),
                ('title_en', models.CharField(blank=True, max_length=160, verbose_name='Sarlavha (EN)')),
                ('arabic', models.TextField(blank=True, verbose_name='Arabcha matn')),
                ('transliteration', models.TextField(blank=True, verbose_name="O'qilishi")),
                ('meaning', models.TextField(verbose_name="Ma'nosi")),
                ('meaning_en', models.TextField(blank=True, verbose_name="Ma'nosi (EN)")),
                ('source', models.CharField(blank=True, max_length=160, verbose_name='Manba')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_visible', models.BooleanField(default=True, verbose_name="Ko'rinadi")),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duas', to='invitation.wedding')),
            ],
            options={
                'verbose_name': 'Duo',
                'verbose_name_plural': 'Duolar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
