# Generated by Django 5.1.4 on 2026-09-05 19:22

import invitation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_dua'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='hero_image',
            field=models.ImageField(blank=True, help_text="Bo'sh qolsa umumiy bosh rasm ko'rsatiladi.", upload_to=invitation.models.hero_path, verbose_name='Shaxsiy bosh rasm'),
        ),
        migrations.AddField(
            model_name='guest',
            name='music',
            field=models.FileField(blank=True, help_text="Bo'sh qolsa umumiy musiqa qo'yiladi.", upload_to=invitation.models.music_path, verbose_name='Shaxsiy musiqa'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='wishes_need_approval',
            field=models.BooleanField(default=True, help_text="Belgilangan bo'lsa, yangi tilak siz tasdiqlamaguningizcha sahifada ko'rinmaydi.", verbose_name="Tilaklar tasdiqdan o'tsin"),
        ),
        migrations.AlterField(
            model_name='wish',
            name='is_visible',
            field=models.BooleanField(default=False, help_text="Belgilanmagan tilak faqat sizga ko'rinadi.", verbose_name="Sahifada ko'rinadi"),
        ),
    ]
