# Generated by Django 5.1.4 on 2026-10-04 01:22

import invitation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitation", "0005_guest_hero_image_guest_music_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wedding",
            name="labels",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Bo\'lim sarlavhalari va tugma yozuvlari: {"uz": {...}, "en": {...}}',
                verbose_name="Sahifa yozuvlari",
            ),
        ),
        migrations.AlterField(
            model_name="guestupload",
            name="file",
            field=models.FileField(
                storage=invitation.models.get_private_storage,
                upload_to=invitation.models.guest_upload_path,
                verbose_name="Fayl",
            ),
        ),
    ]
